### ISSUE TITLE
Dynmap custom link

### ISSUE THREAD

**Issue by Lemon4ik6484** [vincss/mcsleepingserverstarter#174]
Can you make ability to put your own link to dynmap button in web-gui cuz it will be easier to setup it. 
Or make video tutorial, sorry i'm too stupid for text guides :(

**Comment by vincss** [comment]
Hi !
What are you trying to achieve ? 
You already have a dynmap setup on a separate hosting service ?
The purpose of the dynmap is to host it by the sleeping server instead of MC/Apache/Nginx/...
https://github.com/vincss/mcsleepingserverstarter/wiki/Use-internal-SSS-WebServer-for-dynmap
Do not hesitate to add suggestions to the wiki.

**Comment by Lemon4ik6484** [comment]
Hi !
I mean it will be cool if in **sleepingSettings.yml** it will be atribute like "dynmap-url" just to put link to your dynmap (like "ip:port") and it will open in new tab without webserver

**Comment by vincss** [comment]
Ok, I will see what I can do. :-)

**Comment by vincss** [comment]
Hi,
It's done : https://github.com/vincss/mcsleepingserverstarter/releases
Can you give it a try ?

**Comment by Lemon4ik6484** [comment]
Hi, tysm
sure
