### ISSUE TITLE
How to allow Bedrock Players start the Minecraft Server (GeyserMC)?

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#189]
I wanted that the Bedrock players could also start the Server.

**Comment by vincss** [comment]
https://github.com/vincss/mcsleepingserverstarter/issues/130

**Comment by SkyKingPX** [comment]
Didn‘t help me @vincss

**Comment by JonathanRMartinezHernandez** [comment]
I too have this problem I believe. I am running a Java server, I am using the exe file to wake the server up, I'm also using GeyserMC and Floodgate to allow Bedrock players to join. They can join perfectly fine if the server is awake but they cannot wake up the server, it seems that it needs to be a Java account that wakes the server up as the server asks if Floodgate is configured correctly (it is, that's why Bedrock players are able to join).  
  
Could this be do to the auth type that Sleeping Server Starter uses? Is it only listening on the 25565 port and not the Bedrock port?

**Comment by SkyKingPX** [comment]
@JonathanRMartinezHernandez I did the exact same as you. The problem is that the Repo that @vincss uses hasn’t updated to a newer version yet. 

After it finally does, It will also work for Bedrock players on the same Port (25565) to wake up the Server.
