### ISSUE TITLE
TypeScript error 

### ISSUE THREAD

**Issue by ArmoredFuzzball** [vincss/mcsleepingserverstarter#59]
On v1.0.4 with TS 4.4.3, on Arch Linux, npm start produces:
```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:

sleepingSettings.ts:46:50 - error TS2571: Object is of type 'unknown'.

46         logger.error('Failed to write setting.', error.message);
                                                    ~~~~~
sleepingSettings.ts:57:64 - error TS2571: Object is of type 'unknown'.

57         logger.error('Failed to load setting, using default.', error.message);
```
Fix:
add this line in tsconfig.json:
`"useUnknownInCatchVariables": false,`
And npm start launches as normal.

Great program btw!

Edit: Sources
https://stackoverflow.com/a/69445095
https://stackoverflow.com/a/69431651

**Comment by iwa** [comment]
thanks for the bug report!

but we haven't upgraded typescript to the latest version yet, and it seems that you installed a newer one
so to be sure you're not running into bugs cause you're not using the right deps versions, please make sure to use the typescript version installed in `node_modules` and not yours installed globally before reporting an issue

**Comment by Rysanlos** [comment]
I have the same issue with npm version 8.1.0
`    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
sleepingSettings.ts:46:50 - error TS2571: Object is of type 'unknown'.

46         logger.error('Failed to write setting.', error.message);
                                                    ~~~~~
sleepingSettings.ts:57:64 - error TS2571: Object is of type 'unknown'.

57         logger.error('Failed to load setting, using default.', error.message);
                                                                  ~~~~~
`

**Comment by vincss** [comment]
Yes, the issue is that the package-lock.json changed between major releases of npm ( 6 -> 7 -> 8).

npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

I'm going to update with the latest lts which is 8. 
https://nodejs.org/en/download/releases/
